import ScrollFrameSequence from './ScrollFrameSequence';

export default function Hero() {
  // We have exactly 180 frames generated by the conversion script
  return (
    <section id="hero" className="relative w-full bg-[#0a0a0a]">
      <ScrollFrameSequence frameCount={180} />
    </section>
  );
}
